#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/yusefislaih/Documents/Dev/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/yusefislaih/Desktop/MCC/Courses/Flutter_Intermidate/Flutter_Simple_Login"
export "FLUTTER_TARGET=/Users/yusefislaih/Desktop/MCC/Courses/Flutter_Intermidate/Flutter_Simple_Login/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/yusefislaih/Documents/Dev/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
